CREATE TABLE IF NOT EXISTS "user" (
  uid VARCHAR(20)  NOT NULL PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS "thing" (
  tid VARCHAR(20) NOT NULL PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS "subscribes" (
  uid VARCHAR(20) NOT NULL REFERENCES "user",
  category VARCHAR(20) NOT NULL,
  PRIMARY KEY(uid,category)
);

CREATE TABLE IF NOT EXISTS "tags" (
  tid VARCHAR(20) NOT NULL REFERENCES "thing",
  tag VARCHAR(15) NOT NULL,
  freq INT NOT NULL,
  PRIMARY KEY (tid,tag)
);

CREATE TABLE IF NOT EXISTS "ratings" (
  uid VARCHAR(20) NOT NULL REFERENCES "user",
  tid VARCHAR(20) NOT NULL REFERENCES "thing",
  rating INT NOT NULL CHECK (rating>=0 AND rating<=5),
  timestamp VARCHAR(30) NOT NULL,
  media TEXT
);

CREATE TABLE IF NOT EXISTS "directory" (
  tid INT NOT NULL REFERENCES "thing",
  category VARCHAR(20) NOT NULL
);  